### ISSUE TITLE
BLE in DGNWG05LM

### ISSUE THREAD

**Issue by martkotur** [openlumi/openlumi.github.io#11]
Tell me, is the BLE implementation expected on the gateway? Will there be support for the node node-red-contrib-xiaomi-ble? the node is not installed now.

**Comment by G1K** [comment]
BLE on the gateway is implemented. You can use it with different solutions. You are asking about node-red-contrib-xiaomi-ble, I tried building it and adding it to node-red, but the results are not very stable. It works very badly on the gateway, maybe it's the drivers or the combined wifi and bluetooth module.

You can view the bluetooth device by typing `hciconfig`

enable interface `hciconfig hci0 up`
or enable in config `/etc/bluetooth/main.conf` `AutoEnable = true`


I tried several different solutions and settled on EspruinoHub. I did some tweaks in the form of supported xiaomi devices and put together a package. You can install it from the openlumi feed

```
opkg update
opkg install node-espurinohub
```
_I was a little mistaken in the name when I was building the package, the other day I will fix it and add options to the config to configure the format of message output in mqtt_


Or try others
https://github.com/devbis/ble2mqtt
https://github.com/Beetle-II/lumi
