### ISSUE TITLE
Does the stock backup include zigbee firmware?

### ISSUE THREAD

**Issue by ha0y** [openlumi/openlumi.github.io#14]
Accroding to the guide, to use zigbee on the gateway, we must flash the firmware for zigbee module. Does the stock backup include zigbee firmware so the stock firmware can work with zigbee modules? Do I need to manually flash zigbee firmware back before restoring to stock?

**Comment by devbis** [comment]
It contains a binary file with firmware for the Zigbee chip. After restoring the firmware you have to reflash with Xiaomi zigbee firmware from /home/root/
