### ISSUE TITLE
Не открывается интерфейс z2mqtt

### ISSUE THREAD

**Issue by Garkus98** [openlumi/openlumi.github.io#19]
Не открывается интерфейс z2mqtt. сделал все по инструкции раньше работало а потом раз и не работает пытался переустанавливать сбрасывал шлюз. но ничего не помогает

**Comment by devbis** [comment]
Вам стоит посмотреть логи запуска zigbee2mqtt на шлюзе или же обратиться к официальной документации https://www.zigbee2mqtt.io/
