### ISSUE TITLE
How to update to last Zigbee2MQTT Version??

### ISSUE THREAD

**Issue by inphower** [openlumi/openlumi.github.io#24]

**Comment by devbis** [comment]
You can find `ipk` for zigbee2mqtt-1.20.0 at https://github.com/openlumi/releases/tree/gh-pages
But this repo isn't updated regularly. 

You can use this repo https://github.com/nxhack/openwrt-node-packages/blob/master/node-zigbee2mqtt/Makefile to build new versions yourself when they are released.
