### ISSUE TITLE
Alarm mode support 

### ISSUE THREAD

**Issue by giltabibian** [openlumi/openlumi.github.io#30]
Hi! Thanks for this great guide! 
I was able to connect to uart and flash the firmware on my DGNWG05LM gateway. Still wondering witch firmware to install.
Cant find any mention of alarm mode support? Is it possible to use it? 
I understand that i cant use both xiaomi mi account and ZHA/z2mqtt. My purpose is to use both the zigbee sensors and the hub alarm and light. (using home assistant on raspberry pi 4)

**Comment by devbis** [comment]
Alarm mode is not implemented. You can use https://github.com/openlumi/lumimqtt to flash light through MQTT and MPD HA integration to play sounds. Also, you can implement a custom shell command with MQTT events.

**Comment by devbis** [comment]
I don't think that stock firmware is customizable in any way

**Comment by giltabibian** [comment]
Ok. And does the stock fw serving as a repeater to all zegbee messages it receives?

**Comment by devbis** [comment]
I don't know, doubt it :)
