### ISSUE TITLE
HA Integration support with DGNWG05LM

### ISSUE THREAD

**Issue by giltabibian** [openlumi/openlumi.github.io#32]
Can i use this integration in home assistant:
https://github.com/AlexxIT/XiaomiGateway3

Using DGNWG05LM gateway and followed those steps to gain root and wifi config. Now i can access remotely without uart:
https://openlumi.github.io/gain_root.html

**Comment by devbis** [comment]
No, you cannot. It is for another model of gateway

**Comment by giltabibian** [comment]
@devbis why not? What is the difference from other gateway?
The integration based on telnet / ssh with root permissions?
So after connecting to UART and fix those for DGNWG05LM model i guess it should work right?
Can you list what are the differences that make it impossible to use this model with this integration?

**Comment by devbis** [comment]
It has completely different hardware (and firmware). Read the manual on the component's page.

**Comment by giltabibian** [comment]
Thanks for the informative comments 😊
