### ISSUE TITLE
I delete /etc/inittab

### ISSUE THREAD

**Issue by Dan81Adrian** [openlumi/openlumi.github.io#38]
Please can you give me the contents of the /etc/inittab
I don't know how I emptied it :(

Now I tried to flashing over USB, and I got stuck here:

## Enter main_loop() Now##
Normal Boot
Hit any key to stop autoboot:  0
=> bmode usb
resetting ...

U-Boot 2020.04-5.4.70-2.3.0+ge42dee801e (Dec 04 2020 - 00:53:33 +0000)

CPU:   i.MX6ULL rev1.1 528 MHz (running at 396 MHz)
CPU:   Commercial temperature grade (0C to 95C) at 47C
Reset cause: WDOG
Model: i.MX6 ULZ 14x14 EVK Board
Board: MX6ULL 14x14 EVK
DRAM:  512 MiB
NAND:  256 MiB
MMC:   FSL_SDHC: 0
Loading Environment from NAND... *** Warning - bad CRC, using default environment

In:    serial
Out:   serial
Err:   serial
Net:   No ethernet found.
Fastboot: Normal
Boot from USB for mfgtools
*** Warning - Use default environment for                                mfgtools
, using default environment

Run bootcmd_mfg: run mfgtool_args;if iminfo ${initrd_addr}; then if test ${tee} = yes; then bootm ${tee_addr} ${initrd_addr} ${fdt_addr}; else bootz ${loadaddr} ${initrd_addr} ${fdt_addr}; fi; else echo "Run fastboot ..."; fastboot 0; fi;
Hit any key to stop autoboot:  0

## Checking Image at 86800000 ...
Unknown image format!
Run fastboot ...
No USB device found
USB init failed: -19
=>

**Comment by devbis** [comment]
Looks like a problem with soldering or wires. Use another USB cable and try again

**Comment by Dan81Adrian** [comment]
I solved it, the cable was the problem, i solder ID pin to ground. Thanks!
