### ISSUE TITLE
Error 255

### ISSUE THREAD

**Issue by BaRaD5** [openlumi/openlumi.github.io#40]
hey!

It seems i cant install any packages no matter which package i try i get error 255
"found, but incompatible with the architectures configured"
help?

**Comment by devbis** [comment]
Maybe feeds are broken. You may want to upgrade/reinstall to the latest 21.02.1 image for your device.

**Comment by BaRaD5** [comment]
> Maybe feeds are broken. You may want to upgrade/reinstall to the latest 21.02.1 image for your device.

I did everything from scrath and it seems to fix it
