### ISSUE TITLE
Gateway seems to crash after booting

### ISSUE THREAD

**Issue by bronks75** [openlumi/openlumi.github.io#48]
Hello,
I have an issue when I boot with bash, the system seems to crash after few seconds.
I can launch 1 command if i go fast but after that no more life.
Can you please help me on this ?

U-Boot 2016.03 (Nov 07 2017 - 20:11:55 +0800)

CPU:   Freescale i.MX6ULL rev1.1 528 MHz (running at 396 MHz)
CPU:   Commercial temperature grade (0C to 95C) at 34C
Reset cause: POR
Board: Lumi international Gateway
I2C:   ready
DRAM:  256 MiB
NAND:  256 MiB
MMC:   FSL_SDHC: 0, FSL_SDHC: 1
*** Warning - bad CRC, using default environment

Display: TFT43AB (480x272)
Video: LCDIF@0x21c8000 is fused, disable it
In:    serial
Out:   serial
Err:   serial
Net:   Ethernet@0x20b4000 is fused, disable it
Board Net Initialization Failed
No ethernet found.

## Enter main_loop() Now##
Normal Boot
Hit any key to stop autoboot:  0
=> setenv bootargs "${bootargs} single rw init=/bin/bash" && boot

NAND read: device 0 offset 0x300000, size 0x700000
 7340032 bytes read: OK

NAND read: device 0 offset 0xa00000, size 0x100000
 1048576 bytes read: OK
Kernel image @ 0x80800000 [ 0x000000 - 0x617290 ]
## Flattened Device Tree blob at 83000000
   Booting using the fdt blob at 0x83000000
   Using Device Tree in place at 83000000, end 8300c0e1
Modify /soc/aips-bus@02000000/tsc@02040000:status disabled
Modify /soc/aips-bus@02000000/can@02090000:status disabled
Modify /soc/aips-bus@02000000/can@02094000:status disabled
Modify /soc/aips-bus@02100000/lcdif@021c8000:status disabled
Modify /soc/aips-bus@02100000/pxp@021cc000:status disabled
Modify /soc/aips-bus@02100000/csi@021c4000:status disabled
Modify /soc/aips-bus@02000000/ethernet@020b4000:status disabled
Modify /soc/aips-bus@02100000/usb@02184200:status disabled
Modify /soc/aips-bus@02000000/spba-bus@02000000/sai@0202c000:status disabled
Modify /soc/aips-bus@02000000/spba-bus@02000000/sai@02030000:status disabled
Modify /soc/aips-bus@02100000/serial@021f4000:status disabled
Modify /soc/aips-bus@02100000/serial@021fc000:status disabled
Modify /soc/aips-bus@02000000/spba-bus@02000000/serial@02018000:status disabled
Modify /soc/aips-bus@02000000/pwm@020f0000:status disabled
Modify /soc/aips-bus@02000000/pwm@020f4000:status disabled
Modify /soc/aips-bus@02000000/pwm@020f8000:status disabled
Modify /soc/aips-bus@02000000/pwm@020fc000:status disabled
Modify /soc/aips-bus@02000000/spba-bus@02000000/ecspi@02010000:status disabled
Modify /soc/aips-bus@02000000/spba-bus@02000000/ecspi@02014000:status disabled
Modify /soc/aips-bus@02100000/i2c@021a8000:status disabled
Modify /soc/aips-bus@02100000/i2c@021f8000:status disabled
Modify /soc/aips-bus@02000000/gpt@020e8000:status disabled
Modify /soc/aips-bus@02000000/epit@020d4000:status disabled
ft_system_setup for mx6
No PMIC found!

Starting kernel ...

[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 4.1.15+gb63f3f5 (chenlong@gitlab) (gcc version 5.3.0 (GCC) ) #37 SMP PREEMPT Tue Jun 19 15:28:38 CST 2018
[    0.000000] CPU: ARMv7 Processor [410fc075] revision 5 (ARMv7), cr=10c53c7d
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] Machine model: Freescale i.MX6 ULL 14x14 EVK Board
[    0.000000] Reserved memory: failed to allocate memory for node 'linux,cma'
[    0.000000] cma: Reserved 96 MiB at 0x8a000000
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] PERCPU: Embedded 12 pages/cpu @89da3000 s16908 r8192 d24052 u49152
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 65024
[    0.000000] Kernel command line: console=ttymxc0,115200 ubi.mtd=3 root=ubi0:rootfs rootfstype=ubifs cma=96M mtdparts=gpmi-nand:3m(boot),7m(kernel),1m(dtb),-(rootfs)  single rw init=/bin/bash
[    0.000000] PID hash table entries: 1024 (order: 0, 4096 bytes)
[    0.000000] Dentry cache hash table entries: 32768 (order: 5, 131072 bytes)
[    0.000000] Inode-cache hash table entries: 16384 (order: 4, 65536 bytes)
[    0.000000] Memory: 148920K/262144K available (8035K kernel code, 423K rwdata, 2812K rodata, 540K init, 426K bss, 14920K reserved, 98304K cma-reserved, 0K highmem)
[    0.000000] Virtual kernel memory layout:
[    0.000000]     vector  : 0xffff0000 - 0xffff1000   (   4 kB)
[    0.000000]     fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
[    0.000000]     vmalloc : 0x90800000 - 0xff000000   (1768 MB)
[    0.000000]     lowmem  : 0x80000000 - 0x90000000   ( 256 MB)
[    0.000000]     pkmap   : 0x7fe00000 - 0x80000000   (   2 MB)
[    0.000000]     modules : 0x7f000000 - 0x7fe00000   (  14 MB)
[    0.000000]       .text : 0x80008000 - 0x80aa01f8   (10849 kB)
[    0.000000]       .init : 0x80aa1000 - 0x80b28000   ( 540 kB)
[    0.000000]       .data : 0x80b28000 - 0x80b91fa0   ( 424 kB)
[    0.000000]        .bss : 0x80b94000 - 0x80bfeb5c   ( 427 kB)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] Preemptible hierarchical RCU implementation.
[    0.000000]  Additional per-CPU info printed with stalls.
[    0.000000]  RCU restricting CPUs from NR_CPUS=4 to nr_cpu_ids=1.
[    0.000000] RCU: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=1
[    0.000000] NR_IRQS:16 nr_irqs:16 16
[    0.000000] mxc_clocksource_init 24000000
[    0.000000] Switching to timer-based delay loop, resolution 41ns
[    0.000015] sched_clock: 32 bits at 24MHz, resolution 41ns, wraps every 89478484971ns
[    0.000057] clocksource mxc_timer1: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 79635851949 ns
[    0.002632] Console: colour dummy device 80x30
[    0.002675] Calibrating delay loop (skipped), value calculated using timer frequency.. 48.00 BogoMIPS (lpj=240000)
[    0.002711] pid_max: default: 32768 minimum: 301
[    0.002947] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.002978] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.004450] CPU: Testing write buffer coherency: ok
[    0.005010] /cpus/cpu@0 missing clock-frequency property
[    0.005058] CPU0: thread -1, cpu 0, socket 0, mpidr 80000000
[    0.005181] Setting up static identity map for 0x80008280 - 0x800082d8
[    0.041259] Brought up 1 CPUs
[    0.041299] SMP: Total of 1 processors activated (48.00 BogoMIPS).
[    0.041320] CPU: All CPU(s) started in SVC mode.
[    0.042539] devtmpfs: initialized
[    0.064826] VFP support v0.3: implementor 41 architecture 2 part 30 variant 7 rev 5
[    0.065779] clocksource jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.074382] pinctrl core: initialized pinctrl subsystem
[    0.077215] NET: Registered protocol family 16
[    0.096089] DMA: preallocated 256 KiB pool for atomic coherent allocations
[    0.121018] cpuidle: using governor ladder
[    0.151077] cpuidle: using governor menu
[    0.195181] hw-breakpoint: found 5 (+1 reserved) breakpoint and 4 watchpoint registers.
[    0.195223] hw-breakpoint: maximum watchpoint size is 8 bytes.
[    0.198500] imx6ul-pinctrl 20e0000.iomuxc: Invalid fsl,pins property in node /soc/aips-bus@02000000/iomuxc@020e0000/imx6ul-evk/hoggrp-1
[    0.199233] imx6ul-pinctrl 20e0000.iomuxc: initialized IMX pinctrl driver
[    0.199956] imx6ul-pinctrl 2290000.iomuxc-snvs: initialized IMX pinctrl driver
[    0.268895] mxs-dma 1804000.dma-apbh: initialized
[    0.275946] SCSI subsystem initialized
[    0.277482] usbcore: registered new interface driver usbfs
[    0.277686] usbcore: registered new interface driver hub
[    0.277925] usbcore: registered new device driver usb
[    0.280608] i2c i2c-0: IMX I2C adapter registered
[    0.280658] i2c i2c-0: can't use DMA
[    0.282531] i2c i2c-1: IMX I2C adapter registered
[    0.282581] i2c i2c-1: can't use DMA
[    0.282914] Linux video capture interface: v2.00
[    0.283159] pps_core: LinuxPPS API ver. 1 registered
[    0.283181] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
[    0.283266] PTP clock support registered
[    0.286058] MIPI CSI2 driver module loaded
[    0.286790] Advanced Linux Sound Architecture Driver Initialized.
[    0.288999] Bluetooth: Core ver 2.20
[    0.289139] NET: Registered protocol family 31
[    0.289164] Bluetooth: HCI device and connection manager initialized
[    0.289208] Bluetooth: HCI socket layer initialized
[    0.289248] Bluetooth: L2CAP socket layer initialized
[    0.289336] Bluetooth: SCO socket layer initialized
[    0.291756] Switched to clocksource mxc_timer1
[    0.319280] NET: Registered protocol family 2
[    0.321033] TCP established hash table entries: 2048 (order: 1, 8192 bytes)
[    0.321140] TCP bind hash table entries: 2048 (order: 2, 16384 bytes)
[    0.321235] TCP: Hash tables configured (established 2048 bind 2048)
[    0.321386] UDP hash table entries: 256 (order: 1, 8192 bytes)
[    0.321454] UDP-Lite hash table entries: 256 (order: 1, 8192 bytes)
[    0.322070] NET: Registered protocol family 1
[    0.325560] imx rpmsg driver is registered.
[    0.328329] Bus freq driver module loaded
[    0.330762] futex hash table entries: 256 (order: 2, 16384 bytes)
[    0.349667] VFS: Disk quotas dquot_6.6.0
[    0.350145] VFS: Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    0.354681] jffs2: version 2.2. (NAND) © 2001-2006 Red Hat, Inc.
[    0.356514] fuse init (API version 7.23)
[    0.368180] io scheduler noop registered
[    0.368232] io scheduler deadline registered
[    0.368805] io scheduler cfq registered (default)
[    0.369894] imx-weim 21b8000.weim: Driver registered.
[    0.375149] lumi_r supply power not found, using dummy regulator
[    0.377067] lumi_b supply power not found, using dummy regulator
[    0.378853] lumi_g supply power not found, using dummy regulator
[    0.381197] MIPI DSI driver module loaded
[    0.381644] MIPI DSI driver module loaded
[    0.387674] imx-sdma 20ec000.sdma: no event needs to be remapped
[    0.387919] imx-sdma 20ec000.sdma: loaded firmware 3.3
[    0.396091] imx-sdma 20ec000.sdma: initialized
[    0.398324] 2020000.serial: ttymxc0 at MMIO 0x2020000 (irq = 19, base_baud = 5000000) is a IMX
[    1.049833] console [ttymxc0] enabled
[    1.055553] 21e8000.serial: ttymxc1 at MMIO 0x21e8000 (irq = 217, base_baud = 5000000) is a IMX
[    1.101689] imx-rng 2284000.rngb: iMX RNG Registered.
[    1.107561] imx sema4 driver is registered.
[    1.112065] [drm] Initialized drm 1.1.0 20060810
[    1.118155] [drm] Initialized vivante 1.0.0 20120216 on minor 0
[    1.152638] brd: module loaded
[    1.170190] loop: module loaded
[    1.174224] pn54x_dev_init-->lumi
[    1.177765] pn54x_probe
[    1.180296] pn544 1-0028: FIRM GPIO <OPTIONAL> error getting from OF node
[    1.187315] pn544 1-0028: CLKREQ GPIO <OPTIONAL> error getting from OF node
[    1.194396] 1-0028 supply nxp,pn54x-pvdd not found, using dummy regulator
[    1.201386] 1-0028 supply nxp,pn54x-vbat not found, using dummy regulator
[    1.208419] 1-0028 supply nxp,pn54x-pmuvcc not found, using dummy regulator
[    1.215571] 1-0028 supply nxp,pn54x-sevdd not found, using dummy regulator
[    1.222632] pn54x_probe: request irq_gpio 7
[    1.226857] pn54x_probe: request ven_gpio 3
[    1.231533] pn54x_probe : requesting IRQ 35
[    1.251649] nand: device found, Manufacturer ID: 0x2c, Chip ID: 0xda
[    1.258163] nand: Micron MT29F2G08ABAEAWP
[    1.262261] nand: 256 MiB, SLC, erase size: 128 KiB, page size: 2048, OOB size: 64
[    1.270740] gpmi-nand 1806000.gpmi-nand: enable the asynchronous EDO mode 5
[    1.278265] Bad block table found at page 131008, version 0x01
[    1.284427] Bad block table found at page 130944, version 0x01
[    1.290679] 4 cmdlinepart partitions found on MTD device gpmi-nand
[    1.296969] Creating 4 MTD partitions on "gpmi-nand":
[    1.302119] 0x000000000000-0x000000300000 : "boot"
[    1.309654] 0x000000300000-0x000000a00000 : "kernel"
[    1.317307] 0x000000a00000-0x000000b00000 : "dtb"
[    1.324680] 0x000000b00000-0x000010000000 : "rootfs"
[    1.333235] gpmi-nand 1806000.gpmi-nand: driver registered.
[    1.345447] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    1.352170] ehci-mxc: Freescale On-Chip EHCI Host driver
[    1.358007] usbcore: registered new interface driver usb-storage
[    1.364331] usbcore: registered new interface driver usb_ehset_test
[    1.373387] 2184800.usbmisc supply vbus-wakeup not found, using dummy regulator
[    1.382653] 2184000.usb supply vbus not found, using dummy regulator
[    1.397434] mousedev: PS/2 mouse device common for all mice
[    1.405304] input: 20cc000.snvs:snvs-powerkey as /devices/platform/soc/2000000.aips-bus/20cc000.snvs/20cc000.snvs:snvs-powerkey/input/input0
[    1.423639] snvs_rtc 20cc000.snvs:snvs-rtc-lp: rtc core: registered 20cc000.snvs:snvs-r as rtc0
[    1.432827] i2c /dev entries driver
[    1.439262] IR NEC protocol handler initialized
[    1.443981] IR RC5(x/sz) protocol handler initialized
[    1.449083] IR RC6 protocol handler initialized
[    1.453714] IR JVC protocol handler initialized
[    1.458298] IR Sony protocol handler initialized
[    1.463007] IR SANYO protocol handler initialized
[    1.467760] IR Sharp protocol handler initialized
[    1.472557] IR MCE Keyboard/mouse protocol handler initialized
[    1.478439] IR XMP protocol handler initialized
[    1.489537] imx2-wdt 20bc000.wdog: use WDOG_B to reboot.
[    1.496034] imx2-wdt 20bc000.wdog: timeout 60 sec (nowayout=0)
[    1.503522] sdhci: Secure Digital Host Controller Interface driver
[    1.509756] sdhci: Copyright(c) Pierre Ossman
[    1.514282] sdhci-pltfm: SDHCI platform and OF driver helper
[    1.521898] /soc/aips-bus@02100000/usdhc@02190000: voltage-ranges unspecified
[    1.529102] sdhci-esdhc-imx 2190000.usdhc: could not get ultra high speed state, work on normal mode
[    1.539749] sdhci-esdhc-imx 2190000.usdhc: No vmmc regulator found
[    1.546065] sdhci-esdhc-imx 2190000.usdhc: No vqmmc regulator found
[    1.592025] mmc0: SDHCI controller on 2190000.usdhc [2190000.usdhc] using ADMA
[    1.627176] usbcore: registered new interface driver usbhid
[    1.633179] usbhid: USB HID core driver
[    1.638093] vf610-adc 2198000.adc: Debug vf610_adc_proble()
[    1.644469] 2198000.adc supply vref not found, using dummy regulator
[    1.651178] vf610-adc 2198000.adc: Debug[0] channels[2]
[    1.666844] wm8524_i2c_probe:
[    1.673566] mmc0: new high speed SDIO card at address 0001
[    1.680073] wm8960 1-001a: Failed to issue reset
[    1.685172] wm8960: probe of 1-001a failed with error -5
[    1.694174] fsl-asrc 2034000.asrc: driver registered
[    1.707321] imx_wm8524_probe:
[    1.711064] wm8524_probe:
[    1.715386] imx-wm8524 sound2: wm8524-hifi <-> 2028000.sai mapping ok
[    1.723644] imx-wm8524 sound2: snd-soc-dummy-dai <-> 2034000.asrc mapping ok
[    1.731025] imx-wm8524 sound2: wm8524-hifi <-> 2028000.sai mapping ok
[    1.745134] NET: Registered protocol family 26
[    1.751968] NET: Registered protocol family 10
[    1.758865] sit: IPv6 over IPv4 tunneling driver
[    1.765673] NET: Registered protocol family 17
[    1.770547] Bluetooth: RFCOMM TTY layer initialized
[    1.775762] Bluetooth: RFCOMM socket layer initialized
[    1.780984] Bluetooth: RFCOMM ver 1.11
[    1.784888] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[    1.790235] Bluetooth: BNEP filters: protocol multicast
[    1.795566] Bluetooth: BNEP socket layer initialized
[    1.800576] Bluetooth: HIDP (Human Interface Emulation) ver 1.2
[    1.806593] Bluetooth: HIDP socket layer initialized
[    1.811607] 8021q: 802.1Q VLAN Support v1.8
[    1.815925] lib80211: common routines for IEEE802.11 drivers
[    1.821888] Key type dns_resolver registered
[    1.828334] cpu cpu0: dev_pm_opp_get_opp_count: device OPP not found (-19)
[    1.860025] ubi0: attaching mtd3
[    2.198477] random: nonblocking pool is initialized
[    2.561343] ubi0: scanning is finished
[    2.580508] ubi0: attached mtd3 (name "rootfs", size 245 MiB)
[    2.586474] ubi0: PEB size: 131072 bytes (128 KiB), LEB size: 126976 bytes
[    2.593443] ubi0: min./max. I/O unit sizes: 2048/2048, sub-page size 2048
[    2.600267] ubi0: VID header offset: 2048 (aligned 2048), data offset: 4096
[    2.607322] ubi0: good PEBs: 1956, bad PEBs: 4, corrupted PEBs: 0
[    2.613608] ubi0: user volume: 1, internal volumes: 1, max. volumes count: 128
[    2.620866] ubi0: max/mean erase counter: 43/13, WL threshold: 4096, image sequence number: 1813099077
[    2.630253] ubi0: available PEBs: 0, total reserved PEBs: 1956, PEBs reserved for bad PEB handling: 36
[    2.639657] ubi0: background thread "ubi_bgt0d" started, PID 73
[    2.645712] dhd_module_init in
[    2.651110] input: regulators:gpio-keys as /devices/platform/regulators/regulators:gpio-keys/input/input1
[    2.662216] snvs_rtc 20cc000.snvs:snvs-rtc-lp: setting system clock to 1970-01-01 01:01:14 UTC (3674)
[    2.693439] gpio_dvfs: disabling
[    2.696728] vref-3v3: disabling
[    2.699891] can-3v3: disabling
[    2.703447] ALSA device list:
[    2.706449]   #0: wm8524-audio
[    2.712011] UBIFS (ubi0:0): background thread "ubifs_bgt0_0" started, PID 74
[    2.740458] UBIFS (ubi0:0): recovery needed
[    2.822768] UBIFS (ubi0:0): recovery completed
[    2.827489] UBIFS (ubi0:0): UBIFS: mounted UBI device 0, volume 0, name "rootfs"
[    2.835112] UBIFS (ubi0:0): LEB size: 126976 bytes (124 KiB), min./max. I/O unit sizes: 2048 bytes/2048 bytes
[    2.845184] UBIFS (ubi0:0): FS size: 241635328 bytes (230 MiB, 1903 LEBs), journal size 12062720 bytes (11 MiB, 95 LEBs)
[    2.856126] UBIFS (ubi0:0): reserved for root: 4952683 bytes (4836 KiB)
[    2.862809] UBIFS (ubi0:0): media format: w4/r0 (latest is w4/r0), UUID AD7DD6E8-1329-4760-93D9-E1A4D3A2465D, small LPT model
[    2.875025] VFS: Mounted root (ubifs filesystem) on device 0:14.
[    2.882132] devtmpfs: mounted
[    2.886251] Freeing unused kernel memory: 540K (80aa1000 - 80b28000)
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
bash-4.3# ls
bin   dev  home  lumi   mnt  proc  sbin  tmp  var
boot  etc  lib   media  opt  run   sys   usr  wpa
bash-4.3#

**Comment by devbis** [comment]
Do you have a log for crash? The log above seems to be booting fine.

**Comment by bronks75** [comment]
Thanks for your answer.
How can I do that, some file to tail (I can launch 1 command before crash) ?

**Comment by devbis** [comment]
You could try to change usb-ttl adapter or the computer. It could be the problem not with the gateway itself.
