### ISSUE TITLE
Zesp32 not load

### ISSUE THREAD

**Issue by felixortegam** [openlumi/openlumi.github.io#57]
I have installed zesp32 following the tutorial, but it doesn't load. I ran the execution from the app directory to check for errors, and here is the result:

![image](https://github.com/user-attachments/assets/5f748a98-7e07-4008-a5ac-8ffbb0e35760)

I have a DGNWG05LM with OpenLumi installed, version OpenLumi 23.05.4 r24012-d8dd03c46f / LuCI openwrt-23.05 branch git-24.086.45142-09d5a38.

Thanks!

**Comment by devbis** [comment]
It might happen that zesp32 is abandoned. The instruction was written several years ago

**Comment by felixortegam** [comment]
Ups! Any good alternative? thanks!

**Comment by devbis** [comment]
It depends on your needs. You can use [home assistant](https://github.com/openlumi/homeassistant_on_openwrt/), zigbee2mqtt, domoticz, [homed](https://wiki.homed.dev/page/ZigBee).

**Comment by felixortegam** [comment]
OK, i have installed lumimqtt and set the zigbee firmware on router mode. Works great with HA in my homelab. Thanks!
