### ISSUE TITLE
 change to router mode

### ISSUE THREAD

**Issue by josejlpd** [openlumi/openlumi.github.io#9]
hello i would like to change the mode of my xiaomi gateway from coordinator to router mode

I have seen in openwrt setup ----> zigbee option a button that says convert to router mode but does not complete the function

Erasing PDM ...
00000000 01 80 02 10 02 10 02 19 9b 02 10 02 10 02 10 12 | ................ |
set device type = router
Starting network scan

**Comment by devbis** [comment]
In fact, the router mode in Zigate works incorrectly.
You can try a router firmware that is already supported in zigbee2mqtt:

https://github.com/igo-r/Lumi-Router-JN5169
